---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
  - repo: local
    hooks:
    - id: generate-readme
      name: Generate Terraform Docs in README
      entry: ./generate-readme
      language: script
      files: ^.*\.tf$
